pipeline:
  build:
    image: kowalatech/ledger
    commands:
      - make
    when:
      event: [push,tag]

  github_release:
    image: plugins/github-release
    secrets: [ github_release_api_key ]
    files: bin/*
    checksum:
      - md5
      - sha1
      - sha256
      - sha512
      - adler32
      - crc32
    when:
      event: tag
